'use strict';

const { contextBridge, ipcRenderer } = require('electron');
const { INVOKE_CHANNELS, SEND_CHANNELS, EVENT_CHANNELS } = require('../shared/ipc-contract');

function invoke(methodName, ...argumentsList) {
  return ipcRenderer.invoke(INVOKE_CHANNELS[methodName], ...argumentsList);
}

function subscribe(methodName, callback) {
  if (typeof callback !== 'function') throw new TypeError(`${methodName} requires a callback`);
  const channel = EVENT_CHANNELS[methodName];
  ipcRenderer.removeAllListeners(channel);
  ipcRenderer.on(channel, (_event, payload) => callback(payload));
}

const api = {
  readDb: () => invoke('readDb'),
  writeDb: (value) => invoke('writeDb', value),
  createDbBackup: () => invoke('createDbBackup'),
  listDbBackups: () => invoke('listDbBackups'),
  restoreDbBackup: (value) => invoke('restoreDbBackup', value),
  writePersonnelImport: (value) => invoke('writePersonnelImport', value),
  restorePersonnelImportVersion: (value) => invoke('restorePersonnelImportVersion', value),
  writeLandImport: (value) => invoke('writeLandImport', value),
  restoreLandImportVersion: (value) => invoke('restoreLandImportVersion', value),
  archiveFile: (value) => invoke('archiveFile', value),
  deleteFile: (sourcePath) => invoke('deleteFile', { sourcePath }),
  moveToTrash: (sourcePath) => invoke('moveToTrash', { sourcePath }),
  restoreFromTrash: (trashPath, originalPath) => invoke('restoreFromTrash', { trashPath, originalPath }),
  deletePermanently: (value) => invoke('deletePermanently', value),
  emptyTrash: () => invoke('emptyTrash'),
  getFilesMetadata: (value) => invoke('getFilesMetadata', value),
  selectFilesAndFolders: () => invoke('selectFilesAndFolders'),
  openPath: (value) => invoke('openPath', value),
  readExcelColumns: (value) => invoke('readExcelColumns', value),
  selectExcelFile: () => invoke('selectExcelFile'),
  selectAndReadContractFeeExcel: () => invoke('selectAndReadContractFeeExcel'),
  importContractFeeAttachments: () => invoke('importContractFeeAttachments'),
  exportContractFeeGroupFiles: (value) => invoke('exportContractFeeGroupFiles', value),
  selectAndReadFarmlandSubsidyExcel: () => invoke('selectAndReadFarmlandSubsidyExcel'),
  exportFarmlandSubsidyWorkbook: (value) => invoke('exportFarmlandSubsidyWorkbook', value),
  getDbDir: () => invoke('getDbDir'),
  startWindowDrag: () => ipcRenderer.send(SEND_CHANNELS.startWindowDrag),
  selectAndMigrateDataDir: () => invoke('selectAndMigrateDataDir'),
  platform: process.platform,
  getMachineId: () => invoke('getMachineId'),
  isDev: () => invoke('isDev'),
  getVersion: () => invoke('getVersion'),
  getLanShareInfo: () => invoke('getLanShareInfo'),
  updateLanShareConfig: (value) => invoke('updateLanShareConfig', value),
  setLanShareAuthState: (value) => invoke('setLanShareAuthState', value),
  writeOperationLog: (value) => invoke('writeOperationLog', value),
  getMobileUploadInfo: () => invoke('getMobileUploadInfo'),
  onMobileFileUploaded: (callback) => subscribe('onMobileFileUploaded', callback),
  onMobileVoiceParseRequest: (callback) => subscribe('onMobileVoiceParseRequest', callback),
  onMobileVoiceConfirmSave: (callback) => subscribe('onMobileVoiceConfirmSave', callback),
  sendVoiceParseResult: (value) => invoke('sendVoiceParseResult', value),
  scanLocalModels: () => invoke('scanLocalModels'),
  toggleInternalAiServer: (value) => invoke('toggleInternalAiServer', value),
  getInternalAiServerStatus: () => invoke('getInternalAiServerStatus'),
  openModelsDir: () => invoke('openModelsDir'),
  appendAiLog: (value) => invoke('appendAiLog', value),
  exportAiLog: (value) => invoke('exportAiLog', value),
  registerLocalAccount: (value) => invoke('registerLocalAccount', value),
  submitUnitAdminApplication: (value) => invoke('submitUnitAdminApplication', value),
  submitMemberApplication: (value) => invoke('submitMemberApplication', value),
  listUnitMemberApplications: () => invoke('listUnitMemberApplications'),
  reviewUnitMemberApplication: (value) => invoke('reviewUnitMemberApplication', value),
  listUnitMembers: () => invoke('listUnitMembers'),
  updateUnitMemberPermissions: (value) => invoke('updateUnitMemberPermissions', value),
  updateUnitMemberStatus: (value) => invoke('updateUnitMemberStatus', value),
  listUnitInvites: () => invoke('listUnitInvites'),
  createUnitInvite: (value) => invoke('createUnitInvite', value),
  deactivateUnitInvite: (value) => invoke('deactivateUnitInvite', value),
  importLocalDataToUnit: () => invoke('importLocalDataToUnit'),
  onUnitWorkspaceChanged: (callback) => subscribe('onUnitWorkspaceChanged', callback),
  loginLocalAccount: (value) => invoke('loginLocalAccount', value),
  logoutLocalAccount: () => invoke('logoutLocalAccount'),
  getLocalAuthStatus: () => invoke('getLocalAuthStatus'),
  getStartupEntitlement: () => invoke('getStartupEntitlement'),
  getLoginPrefill: () => invoke('getLoginPrefill'),
  clearLoginPrefill: () => invoke('clearLoginPrefill'),
  activateOfflineLicense: (code) => invoke('activateOfflineLicense', code),
  listLocalAccountEntitlements: () => invoke('listLocalAccountEntitlements'),
  setLocalAccountEntitlement: (value) => invoke('setLocalAccountEntitlement', value),
  getRemoteServerConfig: () => invoke('getRemoteServerConfig'),
  setRemoteServerConfig: (value) => invoke('setRemoteServerConfig', value),
  checkRemoteServerConnection: (value) => invoke('checkRemoteServerConnection', value),
  getLocalBackendStatus: () => invoke('getLocalBackendStatus'),
  retryLocalBackend: () => invoke('retryLocalBackend'),
  checkForAppUpdate: () => invoke('checkForAppUpdate'),
  downloadAppUpdate: () => invoke('downloadAppUpdate'),
  installAppUpdate: () => invoke('installAppUpdate'),
  onAppUpdateStatus: (callback) => subscribe('onAppUpdateStatus', callback),
  importLocalModel: () => invoke('importLocalModel'),
  getAiSettings: () => invoke('getAiSettings'),
  saveAiSettings: (value) => invoke('saveAiSettings', value),
  testOnlineAi: () => invoke('testOnlineAi'),
  chatWithAi: (messages) => invoke('chatWithAi', { messages }),
  listDocumentTemplates: (documentKind) => invoke('listDocumentTemplates', { documentKind }),
  getDraftLayoutDefaults: (value) => invoke('getDraftLayoutDefaults', value || {}),
  listDraftDocuments: (filters) => invoke('listDraftDocuments', filters || {}),
  getDraftDocument: (documentId) => invoke('getDraftDocument', { documentId }),
  createDraftDocument: (value) => invoke('createDraftDocument', value),
  saveDraftDocument: (value) => invoke('saveDraftDocument', value),
  saveDraftVersion: (value) => invoke('saveDraftVersion', value),
  restoreDraftVersion: (value) => invoke('restoreDraftVersion', value),
  finalizeDraftDocument: (documentId) => invoke('finalizeDraftDocument', { documentId }),
  reopenDraftDocument: (documentId) => invoke('reopenDraftDocument', { documentId }),
  archiveDraftDocument: (documentId) => invoke('archiveDraftDocument', { documentId }),
  recommendDraftReferences: (value) => invoke('recommendDraftReferences', value || {}),
  listDraftBusinessSources: (value) => invoke('listDraftBusinessSources', value || {}),
  generateDraftDocument: (value) => invoke('generateDraftDocument', value),
  converseDraftDocument: (value) => invoke('converseDraftDocument', value),
  createDraftFromHistory: (value) => invoke('createDraftFromHistory', value),
  getWritingProfile: () => invoke('getWritingProfile'),
  saveWritingProfile: (value) => invoke('saveWritingProfile', value),
  resetWritingProfile: () => invoke('resetWritingProfile'),
  exportDraftDocument: (value) => invoke('exportDraftDocument', value),
  printDraftDocument: (value) => invoke('printDraftDocument', value),
  importWorkAttachments: () => invoke('importWorkAttachments'),
};

contextBridge.exposeInMainWorld('api', Object.freeze(api));
