'use strict';

const { contextBridge, ipcRenderer } = require('electron');
const { INVOKE_CHANNELS, SEND_CHANNELS, EVENT_CHANNELS, FOUNDATION_CHANNELS } = require('../shared/ipc-contract');

function invoke(methodName, ...argumentsList) {
  return ipcRenderer.invoke(INVOKE_CHANNELS[methodName], ...argumentsList);
}

function subscribe(methodName, callback) {
  if (typeof callback !== 'function') throw new TypeError(`${methodName} requires a callback`);
  const channel = EVENT_CHANNELS[methodName];
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

const api = {
  readDb: () => invoke('readDb'),
  writeDb: (value) => invoke('writeDb', value),
  createDbBackup: () => invoke('createDbBackup'),
  listDbBackups: () => invoke('listDbBackups'),
  restoreDbBackup: (value) => invoke('restoreDbBackup', value),
  writePersonnelImport: (value) => invoke('writePersonnelImport', value),
  restorePersonnelImportVersion: (value) => invoke('restorePersonnelImportVersion', value),
  writeLandImport: (value) => invoke('writeLandImport', value),
  restoreLandImportVersion: (value) => invoke('restoreLandImportVersion', value),
  archiveFile: (value) => invoke('archiveFile', value),
  deleteFile: (sourcePath) => invoke('deleteFile', { sourcePath }),
  moveToTrash: (sourcePath) => invoke('moveToTrash', { sourcePath }),
  restoreFromTrash: (trashPath, originalPath) => invoke('restoreFromTrash', { trashPath, originalPath }),
  deletePermanently: (value) => invoke('deletePermanently', value),
  emptyTrash: () => invoke('emptyTrash'),
  getFilesMetadata: (value) => invoke('getFilesMetadata', value),
  selectFilesAndFolders: () => invoke('selectFilesAndFolders'),
  openPath: (value) => invoke('openPath', value),
  readExcelColumns: (value) => invoke('readExcelColumns', value),
  selectExcelFile: () => invoke('selectExcelFile'),
  selectAndReadContractFeeExcel: () => invoke('selectAndReadContractFeeExcel'),
  selectAndReadDisbursementExcel: () => invoke('selectAndReadDisbursementExcel'),
  exportTemplateDisbursementWorkbook: (value) => invoke('exportTemplateDisbursementWorkbook', value),
  listDisbursementPrinters: () => invoke('listDisbursementPrinters'),
  printDisbursementPages: (value) => invoke('printDisbursementPages', value),
  importContractFeeAttachments: () => invoke('importContractFeeAttachments'),
  exportContractFeeGroupFiles: (value) => invoke('exportContractFeeGroupFiles', value),
  exportContractFeeProjectWorkbook: (value) => invoke('exportContractFeeProjectWorkbook', value),
  selectAndReadFarmlandSubsidyExcel: () => invoke('selectAndReadFarmlandSubsidyExcel'),
  exportFarmlandSubsidyWorkbook: (value) => invoke('exportFarmlandSubsidyWorkbook', value),
  getDbDir: () => invoke('getDbDir'),
  startWindowDrag: () => ipcRenderer.send(SEND_CHANNELS.startWindowDrag),
  selectAndMigrateDataDir: () => invoke('selectAndMigrateDataDir'),
  platform: process.platform,
  getMachineId: () => invoke('getMachineId'),
  isDev: () => invoke('isDev'),
  getVersion: () => invoke('getVersion'),
  getLanShareInfo: () => invoke('getLanShareInfo'),
  updateLanShareConfig: (value) => invoke('updateLanShareConfig', value),
  getAccountPreferences: () => invoke('getAccountPreferences'),
  saveAccountPreferences: (value) => invoke('saveAccountPreferences', value),
  setLanShareAuthState: (value) => invoke('setLanShareAuthState', value),
  writeOperationLog: (value) => invoke('writeOperationLog', value),
  getMobileUploadInfo: () => invoke('getMobileUploadInfo'),
  onMobileFileUploaded: (callback) => subscribe('onMobileFileUploaded', callback),
  onMobileVoiceParseRequest: (callback) => subscribe('onMobileVoiceParseRequest', callback),
  onMobileVoiceConfirmSave: (callback) => subscribe('onMobileVoiceConfirmSave', callback),
  sendVoiceParseResult: (value) => invoke('sendVoiceParseResult', value),
  scanLocalModels: () => invoke('scanLocalModels'),
  toggleInternalAiServer: (value) => invoke('toggleInternalAiServer', value),
  getInternalAiServerStatus: () => invoke('getInternalAiServerStatus'),
  openModelsDir: () => invoke('openModelsDir'),
  appendAiLog: (value) => invoke('appendAiLog', value),
  exportAiLog: (value) => invoke('exportAiLog', value),
  registerLocalAccount: (value) => invoke('registerLocalAccount', value),
  submitUnitAdminApplication: (value) => invoke('submitUnitAdminApplication', value),
  listUnitMemberApplications: () => invoke('listUnitMemberApplications'),
  reviewUnitMemberApplication: (value) => invoke('reviewUnitMemberApplication', value),
  listUnitMembers: () => invoke('listUnitMembers'),
  getUnitPermissionCatalog: () => invoke('getUnitPermissionCatalog'),
  createUnitMember: (value) => invoke('createUnitMember', value),
  resetUnitMemberPassword: (value) => invoke('resetUnitMemberPassword', value),
  updateUnitMemberPermissions: (value) => invoke('updateUnitMemberPermissions', value),
  updateUnitMemberStatus: (value) => invoke('updateUnitMemberStatus', value),
  importLocalDataToUnit: () => invoke('importLocalDataToUnit'),
  onUnitWorkspaceChanged: (callback) => subscribe('onUnitWorkspaceChanged', callback),
  loginLocalAccount: (value) => invoke('loginLocalAccount', value),
  changeLocalAccountPassword: (value) => invoke('changeLocalAccountPassword', value),
  logoutLocalAccount: () => invoke('logoutLocalAccount'),
  getLocalAuthStatus: () => invoke('getLocalAuthStatus'),
  getStartupEntitlement: () => invoke('getStartupEntitlement'),
  getLoginPrefill: () => invoke('getLoginPrefill'),
  clearLoginPrefill: () => invoke('clearLoginPrefill'),
  activateOfflineLicense: (code) => invoke('activateOfflineLicense', code),
  listLocalAccountEntitlements: () => invoke('listLocalAccountEntitlements'),
  setLocalAccountEntitlement: (value) => invoke('setLocalAccountEntitlement', value),
  getRemoteServerConfig: () => invoke('getRemoteServerConfig'),
  setRemoteServerConfig: (value) => invoke('setRemoteServerConfig', value),
  checkRemoteServerConnection: (value) => invoke('checkRemoteServerConnection', value),
  getLocalBackendStatus: () => invoke('getLocalBackendStatus'),
  retryLocalBackend: () => invoke('retryLocalBackend'),
  checkForAppUpdate: () => invoke('checkForAppUpdate'),
  downloadAppUpdate: () => invoke('downloadAppUpdate'),
  installAppUpdate: () => invoke('installAppUpdate'),
  onAppUpdateStatus: (callback) => subscribe('onAppUpdateStatus', callback),
  importLocalModel: () => invoke('importLocalModel'),
  getAiSettings: () => invoke('getAiSettings'),
  saveAiSettings: (value) => invoke('saveAiSettings', value),
  testOnlineAi: () => invoke('testOnlineAi'),
  getAiQuota: () => invoke('getAiQuota'),
  getAiUsageDetail: (value) => invoke('getAiUsageDetail', value || {}),
  getAiQuotaLedger: (value) => invoke('getAiQuotaLedger', value || {}),
  getAiModels: () => invoke('getAiModels'),
  estimateAiUsage: (value) => invoke('estimateAiUsage', value || {}),
  chatWithAi: (messages) => invoke('chatWithAi', { messages }),
  converseWithAiAssistant: (value) => invoke('converseWithAiAssistant', Array.isArray(value) ? { messages: value } : value),
  listAiAssistantOperations: (value) => invoke('listAiAssistantOperations', value || {}),
  undoAiAssistantOperation: (value) => invoke('undoAiAssistantOperation', value),
  getAiAssistantConversation: (value) => invoke('getAiAssistantConversation', value || {}),
  saveAiAssistantConversation: (value) => invoke('saveAiAssistantConversation', value || {}),
  listAiAssistantMemories: () => invoke('listAiAssistantMemories'),
  deleteAiAssistantMemory: (value) => invoke('deleteAiAssistantMemory', value || {}),
  selectAiAssistantFiles: (value) => invoke('selectAiAssistantFiles', value || {}),
  listAiAssistantFiles: (value) => invoke('listAiAssistantFiles', value || {}),
  previewAiFileImport: (value) => invoke('previewAiFileImport', value || {}),
  confirmAiFileImport: (value) => invoke('confirmAiFileImport', value || {}),
  prepareAiBusinessFile: (value) => invoke('prepareAiBusinessFile', value || {}),
  reviewAiFileOcr: (value) => invoke('reviewAiFileOcr', value || {}),
  confirmAiFileOcrReview: (value) => invoke('confirmAiFileOcrReview', value || {}),
  prepareAiDocumentHandoff: (value) => invoke('prepareAiDocumentHandoff', value || {}),
  applyAiFileCategory: (value) => invoke('applyAiFileCategory', value || {}),
  undoAiFileCategory: (value) => invoke('undoAiFileCategory', value || {}),
  previewAiCertificateTemplate: (value) => invoke('previewAiCertificateTemplate', value || {}),
  applyAiCertificateTemplate: (value) => invoke('applyAiCertificateTemplate', value || {}),
  describeAiImage: (value) => invoke('describeAiImage', value || {}),
  getAiStorageOverview: () => invoke('getAiStorageOverview'),
  cleanAiTemporaryCache: () => invoke('cleanAiTemporaryCache'),
  rebuildAiFileIndex: () => invoke('rebuildAiFileIndex'),
  scanAiAnomalies: () => invoke('scanAiAnomalies'),
  listAiAnomalyFindings: (value) => invoke('listAiAnomalyFindings', value || {}),
  updateAiAnomalyFinding: (value) => invoke('updateAiAnomalyFinding', value || {}),
  draftCertificateWithAi: (value) => invoke('draftCertificateWithAi', value || {}),
  listDocumentTemplates: (documentKind) => invoke('listDocumentTemplates', { documentKind }),
  getDraftLayoutDefaults: (value) => invoke('getDraftLayoutDefaults', value || {}),
  listDraftDocuments: (filters) => invoke('listDraftDocuments', filters || {}),
  getDraftDocument: (documentId) => invoke('getDraftDocument', { documentId }),
  createDraftDocument: (value) => invoke('createDraftDocument', value),
  saveDraftDocument: (value) => invoke('saveDraftDocument', value),
  saveDraftVersion: (value) => invoke('saveDraftVersion', value),
  restoreDraftVersion: (value) => invoke('restoreDraftVersion', value),
  finalizeDraftDocument: (documentId) => invoke('finalizeDraftDocument', { documentId }),
  reopenDraftDocument: (documentId) => invoke('reopenDraftDocument', { documentId }),
  archiveDraftDocument: (documentId) => invoke('archiveDraftDocument', { documentId }),
  recommendDraftReferences: (value) => invoke('recommendDraftReferences', value || {}),
  listDraftBusinessSources: (value) => invoke('listDraftBusinessSources', value || {}),
  generateDraftDocument: (value) => invoke('generateDraftDocument', value),
  converseDraftDocument: (value) => invoke('converseDraftDocument', value),
  createDraftFromHistory: (value) => invoke('createDraftFromHistory', value),
  getWritingProfile: () => invoke('getWritingProfile'),
  saveWritingProfile: (value) => invoke('saveWritingProfile', value),
  resetWritingProfile: () => invoke('resetWritingProfile'),
  exportDraftDocument: (value) => invoke('exportDraftDocument', value),
  printDraftDocument: (value) => invoke('printDraftDocument', value),
  selectCertificateWordTemplate: (value) => invoke('selectCertificateWordTemplate', value),
  inspectCertificateWordTemplate: (value) => invoke('inspectCertificateWordTemplate', value),
  exportCertificateDocument: (value) => invoke('exportCertificateDocument', value),
  printCertificateDocument: (value) => invoke('printCertificateDocument', value),
  importWorkAttachments: () => invoke('importWorkAttachments'),
};

for (const [name, channel] of Object.entries(FOUNDATION_CHANNELS)) api[name] = value => ipcRenderer.invoke(channel, value);
contextBridge.exposeInMainWorld('api', Object.freeze(api));
