'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const test=require('node:test');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'account-directory-'));
process.env.DB_PATH=path.join(temp,'test.db');
process.env.JWT_SECRET='account-directory-test';
const db=require('../src/database');
const directory=require('../src/services/adminAccountDirectory');
const user=(id,role,extras={})=>({id,role,phone:id,name:id,is_active:1,created_at:'2026-01-01',password_hash:'must-not-leak',...extras});
test('主账号分组、成员搜索、分页、创建依据及手机号变化',t=>{
  t.after(()=>{db.flushNow();process.removeAllListeners('beforeExit');fs.rmSync(temp,{recursive:true,force:true});});
  for(const row of [user('main-a','main_account'),user('main-b','main_account'),user('admin','admin'),user('child-a','member',{main_account_id:'main-a',created_by:'admin',position_preset:'custom'}),user('child-b','member',{main_account_id:'main-a',is_active:0}),user('child-c','member',{main_account_id:'main-b'}),user('orphan','member',{main_account_id:'missing'})])db.insert('users',row);
  db.insert('audit_logs',{id:'audit',user_id:'main-b',action:'create_unit_member',target:'child-c',created_at:'2026-01-01'});
  const listed=directory.list();
  assert.deepEqual(listed.accounts.map(x=>x.id).sort(),['main-a','main-b']);
  assert.equal(listed.accounts.find(x=>x.id==='main-a').memberCount,2);
  assert.equal(directory.list({keyword:'child-a'}).accounts[0].id,'main-a');
  assert.equal(directory.list({page:99,pageSize:1}).pagination.page,2);
  assert.equal(directory.list({scope:'unassigned'}).accounts[0].id,'orphan');
  const detail=directory.detail('main-a');
  assert.deepEqual(detail.members.map(x=>x.id).sort(),['child-a','child-b']);
  assert.equal(detail.members.find(x=>x.id==='child-a').createdBy,'admin');
  assert.equal(detail.members.find(x=>x.id==='child-a').positionPreset,'custom');
  assert.equal(detail.members.find(x=>x.id==='child-b').creatorSource,'unknown');
  assert.equal(directory.detail('main-b').members[0].creatorSource,'audit');
  assert.equal(directory.detail('main-a',{isActive:'false'}).members.length,1);
  assert.equal(JSON.stringify(detail).includes('must-not-leak'),false);
  db.updateById('users','main-a',{phone:'13900001111'});
  assert.equal(directory.detail('main-a').members[0].parentPhone,'13900001111');
  assert.throws(()=>directory.detail('child-a'),e=>e.statusCode===404);
});
