'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const test = require('node:test');

const appRoot = path.resolve(__dirname, '..', '..');

test('renderer loads the dual AI settings adapter', async () => {
  const html = await fs.readFile(path.join(appRoot, 'src', 'renderer', 'index.html'), 'utf8');
  assert.match(html, /<script src="js\/ai-settings-ui\.js"><\/script>/u);
  const source = await fs.readFile(path.join(appRoot, 'src', 'renderer', 'js', 'ai-settings-ui.js'), 'utf8');
  assert.match(source, /自动：本地优先/u);
  assert.match(source, /importLocalModel/u);
  assert.match(source, /chatWithAi/u);
  assert.match(source, /communityAiTestStatus/u);
  assert.match(source, /appendConfirmationCard/u);
  assert.match(source, /确认执行/u);
  assert.match(source, /继续执行/u);
  assert.match(source, /AI 助理记录/u);
  assert.match(source, /全部状态/u);
  assert.match(source, /data-ai-assistant-operation-type/u);
  assert.match(source, /work_item_status_update/u);
  assert.match(source, /work_items_soft_delete_batch/u);
  assert.match(source, /database_backup_restore/u);
  assert.match(source, /unit_member_disable/u);
  assert.match(source, /finance_records_clear/u);
  assert.match(source, /certificate_record_delete/u);
  assert.match(source, /finance_record_update/u);
  assert.match(source, /data-ai-assistant-operation-date/u);
  assert.match(source, /查看详情/u);
  assert.match(source, /MAX_CONVERSATION_MESSAGES = 60/u);
  assert.match(source, /MAX_RENDERED_CHAT_ITEMS = 80/u);
  assert.match(source, /appendPendingChatBubble/u);
  assert.match(source, /appendQueryEvidenceCard/u);
  assert.match(source, /查看原始台账/u);
  assert.match(source, /queryEvidence/u);
  assert.match(source, /record-evidence/u);
  assert.match(source, /openEvidenceSource/u);
  assert.match(source, /searchFinanceRecord/u);
  assert.match(source, /searchLand/u);
  assert.match(source, /searchPersonnel/u);
  assert.match(source, /searchPartyKeyword/u);
  assert.match(source, /renderPartyMemberList/u);
  assert.match(source, /openRecordSource/u);
  assert.match(source, /WorkManagement\?\.openWork/u);
  assert.match(source, /DocumentDrafting\?\.openDocument/u);
  assert.match(source, /showCertHistoryModal/u);
  assert.match(source, /certHistoryKeyword/u);
  assert.match(source, /recordSource\?\.kind === 'duty'/u);
  assert.match(source, /dutyFlexibleState\.activeWeekOffset/u);
  assert.match(source, /renderFlexibleDuty/u);
  assert.match(source, /已等待 \$\{seconds\} 秒/u);
  assert.match(source, /converseWithAiAssistant\(conversation\)/u);
  assert.match(source, /新建对话/u);
  assert.match(source, /const button = event\.currentTarget/u);
  assert.match(source, /configureSafeDrawerToggle/u);
  assert.match(source, /removeAttribute\('onclick'\)/u);
  assert.match(source, /stopPropagation/u);
  assert.match(source, /stopImmediatePropagation/u);
  assert.match(source, /addEventListener\('click', closeDrawer, true\)/u);
  assert.match(source, /toggleDesktopAiDrawer = toggleDrawer/u);
  assert.doesNotMatch(source, /new MutationObserver\(\(\) => \{ if \(drawer\.classList\.contains\('hidden'\)\) resetPosition\(\); \}\)/u);
  assert.doesNotMatch(source, /finally\s*\{\s*event\.currentTarget/u);
  assert.doesNotMatch(source, /ipcRenderer|require\(/u);
});
