'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {FoundationBusinessService}=require('../../src/main/foundation-business-service');
function setup(authorize=async()=>{}){let data={personnel:[{id:'resident',name:'合成居民',id_card:'SYNTHETIC',phone:'old',bankAccounts:[{id:'bank',cardNumber:'SYNTHETIC-OLD'}],customFields:{kept:'保留'},disbursementHistory:[{id:'paid',amountCents:12300}]}],residentCustomFields:[{id:'contact',name:'联系人',type:'text'}]};return{data:()=>data,service:new FoundationBusinessService({authorize,store:{read:async()=>structuredClone(data),update:async fn=>{const draft=structuredClone(data),result=await fn(draft);data=draft;return{result};}}})};}
const request=(service,method,body)=>service.request({method,path:'/api/v3/people/editor'+(method==='GET'?'?id=resident':''),body});
test('resident editor saves native fields, accounts and custom values together and retains payment history',async()=>{const {service,data}=setup(),snapshot=(await request(service,'GET')).data;const result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields:{name:'合成居民',idCard:'SYNTHETIC',phone:'new'},accountChanges:{bankAccounts:[{id:'bank',cardNumber:'SYNTHETIC-NEW'}]},customValues:{contact:'测试联系人'},customFields:snapshot.customFields,customFieldsVersion:snapshot.customFieldsVersion});assert.equal(result.ok,true);assert.equal(data().personnel[0].phone,'new');assert.equal(data().personnel[0].bankAccounts[0].cardNumber,'SYNTHETIC-NEW');assert.equal(data().personnel[0].customFields.contact,'测试联系人');assert.equal(data().personnel[0].disbursementHistory[0].amountCents,12300);});
test('a stale resident version rejects all basic and account changes',async()=>{const {service,data}=setup(),snapshot=(await request(service,'GET')).data;data().personnel[0].phone='concurrent';const result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields:{name:'错误覆盖'},accountChanges:{bankAccounts:[]}});assert.equal(result.ok,false);assert.equal(result.error.code,'VERSION_CONFLICT');assert.equal(data().personnel[0].phone,'concurrent');assert.equal(data().personnel[0].bankAccounts.length,1);});
test('editing global field definitions requires settings permission and rolls back all changes',async()=>{const {service,data}=setup(async scope=>{if(scope.path==='/system-settings')throw Error('无权限');}),snapshot=(await request(service,'GET')).data;const result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields:{name:'不能保存'},customFields:[],customFieldsVersion:snapshot.customFieldsVersion});assert.equal(result.ok,false);assert.equal(data().personnel[0].name,'合成居民');assert.equal(data().residentCustomFields.length,1);});
test('identity correction requires two confirmations and leaves the resident untouched when either is missing',async()=>{const {service,data}=setup(),snapshot=(await request(service,'GET')).data;const fields={name:'合成居民',idCard:'11010519491231002X'};let result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields});assert.equal(result.ok,false);assert.equal(result.error.code,'IDENTITY_CONFIRM_REQUIRED');assert.equal(data().personnel[0].id_card,'SYNTHETIC');result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields,identityChangeConfirmation:{firstConfirmed:true,previousIdCard:'SYNTHETIC',newIdCard:'11010519491231002X'}});assert.equal(result.ok,false);assert.equal(result.error.code,'IDENTITY_CONFIRM_REQUIRED');assert.equal(data().personnel[0].id_card,'SYNTHETIC');});
test('confirmed identity correction keeps stable links and records the old and new identity',async()=>{const {service,data}=setup(),snapshot=(await request(service,'GET')).data;const result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields:{name:'合成居民',idCard:'11010519491231002X',birthDate:'2000-01-01',gender:'男'},identityChangeConfirmation:{firstConfirmed:true,secondConfirmed:true,previousIdCard:'SYNTHETIC',newIdCard:'11010519491231002X'}});assert.equal(result.ok,true);const person=data().personnel[0];assert.equal(person.id,'resident');assert.equal(person.idCard,'11010519491231002X');assert.equal(person.id_card,'11010519491231002X');assert.equal(person.birthDate,'1949-12-31');assert.equal(person.birth_date,'1949-12-31');assert.equal(person.gender,'女');assert.equal(person.bankAccounts[0].id,'bank');assert.equal(person.disbursementHistory[0].id,'paid');assert.equal(person.identityCardHistory[0].previousIdCard,'SYNTHETIC');assert.equal(person.residentOperationLog[0].action,'更正身份证号');assert.equal(person.residentOperationLog[0].confirmedTwice,true);});
test('identity correction rejects an invalid card even after confirmation',async()=>{const {service,data}=setup(),snapshot=(await request(service,'GET')).data;const result=await request(service,'PATCH',{id:'resident',baseVersion:snapshot.version,fields:{name:'合成居民',idCard:'110105194912310021'},identityChangeConfirmation:{firstConfirmed:true,secondConfirmed:true,previousIdCard:'SYNTHETIC',newIdCard:'110105194912310021'}});assert.equal(result.ok,false);assert.equal(result.error.code,'INVALID_ID_CARD');assert.equal(data().personnel[0].id_card,'SYNTHETIC');});
